[build]
  # This folder is cached between builds
  publish = "_site"
  command = "gem install bundler && bundle install && JEKYLL_ENV=production bundle exec jekyll build"
  functions = "form-handler"

[build.environment]
  RUBY = "3.2.2"
  NODE_VERSION = "16"
  # Disable version auto-detection entirely
  MISE_AUTO_INSTALL = "false"
  MISE_DISABLE_TOOLS = "python,ruby"
  # Legacy compatibility
  USE_RUBY_LATEST = "false"

# Redirects for the function
[[redirects]]
  from = "/form-api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Default redirect for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 