[build]
  # This folder is cached between builds
  publish = "_site"
  command = "./netlify-build.sh"
  functions = "form-handler"

[build.environment]
  JEKYLL_ENV = "production"
  RUBY_VERSION = "2.7.8"
  BUNDLER_VERSION = "2.3.26"
  NODE_VERSION = "16"
  LANG = "en_US.UTF-8"
  FORCE_RUNTIME = "ruby"

# Redirects for the function
[[redirects]]
  from = "/form-api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Default redirect for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 