[build]
  # This folder is cached between builds
  publish = "_site"
  command = "JEKYLL_ENV=production bundle exec jekyll build"
  functions = "form-handler"

[build.environment]
  RUBY_VERSION = "3.2.2"
  NODE_VERSION = "16"
  NPM_VERSION = "8"

# Redirects for the function
[[redirects]]
  from = "/form-api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# The following redirect is intended for use with most SPAs that handle
# routing internally.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 